// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: pkg/proto/v1/animals.proto

package animalsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnimalsService_GetAnimal_FullMethodName    = "/pkg.proto.v1.AnimalsService/GetAnimal"
	AnimalsService_CreateAnimal_FullMethodName = "/pkg.proto.v1.AnimalsService/CreateAnimal"
)

// AnimalsServiceClient is the client API for AnimalsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnimalsServiceClient interface {
	GetAnimal(ctx context.Context, in *GetAnimalRequest, opts ...grpc.CallOption) (*GetAnimalResponse, error)
	CreateAnimal(ctx context.Context, in *CreateAnimalRequest, opts ...grpc.CallOption) (*CreateAnimalResponse, error)
}

type animalsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimalsServiceClient(cc grpc.ClientConnInterface) AnimalsServiceClient {
	return &animalsServiceClient{cc}
}

func (c *animalsServiceClient) GetAnimal(ctx context.Context, in *GetAnimalRequest, opts ...grpc.CallOption) (*GetAnimalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnimalResponse)
	err := c.cc.Invoke(ctx, AnimalsService_GetAnimal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animalsServiceClient) CreateAnimal(ctx context.Context, in *CreateAnimalRequest, opts ...grpc.CallOption) (*CreateAnimalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAnimalResponse)
	err := c.cc.Invoke(ctx, AnimalsService_CreateAnimal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimalsServiceServer is the server API for AnimalsService service.
// All implementations must embed UnimplementedAnimalsServiceServer
// for forward compatibility.
type AnimalsServiceServer interface {
	GetAnimal(context.Context, *GetAnimalRequest) (*GetAnimalResponse, error)
	CreateAnimal(context.Context, *CreateAnimalRequest) (*CreateAnimalResponse, error)
	mustEmbedUnimplementedAnimalsServiceServer()
}

// UnimplementedAnimalsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnimalsServiceServer struct{}

func (UnimplementedAnimalsServiceServer) GetAnimal(context.Context, *GetAnimalRequest) (*GetAnimalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnimal not implemented")
}
func (UnimplementedAnimalsServiceServer) CreateAnimal(context.Context, *CreateAnimalRequest) (*CreateAnimalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAnimal not implemented")
}
func (UnimplementedAnimalsServiceServer) mustEmbedUnimplementedAnimalsServiceServer() {}
func (UnimplementedAnimalsServiceServer) testEmbeddedByValue()                        {}

// UnsafeAnimalsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnimalsServiceServer will
// result in compilation errors.
type UnsafeAnimalsServiceServer interface {
	mustEmbedUnimplementedAnimalsServiceServer()
}

func RegisterAnimalsServiceServer(s grpc.ServiceRegistrar, srv AnimalsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnimalsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnimalsService_ServiceDesc, srv)
}

func _AnimalsService_GetAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalsServiceServer).GetAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnimalsService_GetAnimal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalsServiceServer).GetAnimal(ctx, req.(*GetAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnimalsService_CreateAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalsServiceServer).CreateAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnimalsService_CreateAnimal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalsServiceServer).CreateAnimal(ctx, req.(*CreateAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnimalsService_ServiceDesc is the grpc.ServiceDesc for AnimalsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnimalsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.proto.v1.AnimalsService",
	HandlerType: (*AnimalsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimal",
			Handler:    _AnimalsService_GetAnimal_Handler,
		},
		{
			MethodName: "CreateAnimal",
			Handler:    _AnimalsService_CreateAnimal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/v1/animals.proto",
}
