// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/proto/v1/animals.proto

package animalsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnimalType int32

const (
	AnimalType_ANIMAL_TYPE_UNSPECIFIED AnimalType = 0
	AnimalType_ANIMAL_TYPE_MAMMALS     AnimalType = 1
	AnimalType_ANIMAL_TYPE_BIRDS       AnimalType = 2
	AnimalType_ANIMAL_TYPE_AMPHIBIANS  AnimalType = 3
	AnimalType_ANIMAL_TYPE_REPTILES    AnimalType = 4
)

// Enum value maps for AnimalType.
var (
	AnimalType_name = map[int32]string{
		0: "ANIMAL_TYPE_UNSPECIFIED",
		1: "ANIMAL_TYPE_MAMMALS",
		2: "ANIMAL_TYPE_BIRDS",
		3: "ANIMAL_TYPE_AMPHIBIANS",
		4: "ANIMAL_TYPE_REPTILES",
	}
	AnimalType_value = map[string]int32{
		"ANIMAL_TYPE_UNSPECIFIED": 0,
		"ANIMAL_TYPE_MAMMALS":     1,
		"ANIMAL_TYPE_BIRDS":       2,
		"ANIMAL_TYPE_AMPHIBIANS":  3,
		"ANIMAL_TYPE_REPTILES":    4,
	}
)

func (x AnimalType) Enum() *AnimalType {
	p := new(AnimalType)
	*p = x
	return p
}

func (x AnimalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnimalType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_v1_animals_proto_enumTypes[0].Descriptor()
}

func (AnimalType) Type() protoreflect.EnumType {
	return &file_pkg_proto_v1_animals_proto_enumTypes[0]
}

func (x AnimalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnimalType.Descriptor instead.
func (AnimalType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_v1_animals_proto_rawDescGZIP(), []int{0}
}

type Animal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AnimalType    AnimalType             `protobuf:"varint,2,opt,name=animal_type,json=animalType,proto3,enum=pkg.proto.v1.AnimalType" json:"animal_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Animal) Reset() {
	*x = Animal{}
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Animal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Animal) ProtoMessage() {}

func (x *Animal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Animal.ProtoReflect.Descriptor instead.
func (*Animal) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_animals_proto_rawDescGZIP(), []int{0}
}

func (x *Animal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Animal) GetAnimalType() AnimalType {
	if x != nil {
		return x.AnimalType
	}
	return AnimalType_ANIMAL_TYPE_UNSPECIFIED
}

func (x *Animal) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetAnimalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimalRequest) Reset() {
	*x = GetAnimalRequest{}
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalRequest) ProtoMessage() {}

func (x *GetAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalRequest.ProtoReflect.Descriptor instead.
func (*GetAnimalRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_animals_proto_rawDescGZIP(), []int{1}
}

type GetAnimalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animal        *Animal                `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnimalResponse) Reset() {
	*x = GetAnimalResponse{}
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnimalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalResponse) ProtoMessage() {}

func (x *GetAnimalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalResponse.ProtoReflect.Descriptor instead.
func (*GetAnimalResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_animals_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnimalResponse) GetAnimal() *Animal {
	if x != nil {
		return x.Animal
	}
	return nil
}

type CreateAnimalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AnimalType    AnimalType             `protobuf:"varint,2,opt,name=animal_type,json=animalType,proto3,enum=pkg.proto.v1.AnimalType" json:"animal_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnimalRequest) Reset() {
	*x = CreateAnimalRequest{}
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimalRequest) ProtoMessage() {}

func (x *CreateAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimalRequest.ProtoReflect.Descriptor instead.
func (*CreateAnimalRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_animals_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAnimalRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAnimalRequest) GetAnimalType() AnimalType {
	if x != nil {
		return x.AnimalType
	}
	return AnimalType_ANIMAL_TYPE_UNSPECIFIED
}

type CreateAnimalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Animal        *Animal                `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnimalResponse) Reset() {
	*x = CreateAnimalResponse{}
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnimalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimalResponse) ProtoMessage() {}

func (x *CreateAnimalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_v1_animals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimalResponse.ProtoReflect.Descriptor instead.
func (*CreateAnimalResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_v1_animals_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAnimalResponse) GetAnimal() *Animal {
	if x != nil {
		return x.Animal
	}
	return nil
}

var File_pkg_proto_v1_animals_proto protoreflect.FileDescriptor

const file_pkg_proto_v1_animals_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/v1/animals.proto\x12\fpkg.proto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n" +
	"\x06Animal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\vanimal_type\x18\x02 \x01(\x0e2\x18.pkg.proto.v1.AnimalTypeR\n" +
	"animalType\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x12\n" +
	"\x10GetAnimalRequest\"A\n" +
	"\x11GetAnimalResponse\x12,\n" +
	"\x06animal\x18\x01 \x01(\v2\x14.pkg.proto.v1.AnimalR\x06animal\"d\n" +
	"\x13CreateAnimalRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\vanimal_type\x18\x02 \x01(\x0e2\x18.pkg.proto.v1.AnimalTypeR\n" +
	"animalType\"D\n" +
	"\x14CreateAnimalResponse\x12,\n" +
	"\x06animal\x18\x01 \x01(\v2\x14.pkg.proto.v1.AnimalR\x06animal*\x8f\x01\n" +
	"\n" +
	"AnimalType\x12\x1b\n" +
	"\x17ANIMAL_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ANIMAL_TYPE_MAMMALS\x10\x01\x12\x15\n" +
	"\x11ANIMAL_TYPE_BIRDS\x10\x02\x12\x1a\n" +
	"\x16ANIMAL_TYPE_AMPHIBIANS\x10\x03\x12\x18\n" +
	"\x14ANIMAL_TYPE_REPTILES\x10\x042\xb5\x01\n" +
	"\x0eAnimalsService\x12L\n" +
	"\tGetAnimal\x12\x1e.pkg.proto.v1.GetAnimalRequest\x1a\x1f.pkg.proto.v1.GetAnimalResponse\x12U\n" +
	"\fCreateAnimal\x12!.pkg.proto.v1.CreateAnimalRequest\x1a\".pkg.proto.v1.CreateAnimalResponseB/Z-github.com/rafikmoreira/animals/pkg;animalsv1b\x06proto3"

var (
	file_pkg_proto_v1_animals_proto_rawDescOnce sync.Once
	file_pkg_proto_v1_animals_proto_rawDescData []byte
)

func file_pkg_proto_v1_animals_proto_rawDescGZIP() []byte {
	file_pkg_proto_v1_animals_proto_rawDescOnce.Do(func() {
		file_pkg_proto_v1_animals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_v1_animals_proto_rawDesc), len(file_pkg_proto_v1_animals_proto_rawDesc)))
	})
	return file_pkg_proto_v1_animals_proto_rawDescData
}

var file_pkg_proto_v1_animals_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_v1_animals_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_proto_v1_animals_proto_goTypes = []any{
	(AnimalType)(0),               // 0: pkg.proto.v1.AnimalType
	(*Animal)(nil),                // 1: pkg.proto.v1.Animal
	(*GetAnimalRequest)(nil),      // 2: pkg.proto.v1.GetAnimalRequest
	(*GetAnimalResponse)(nil),     // 3: pkg.proto.v1.GetAnimalResponse
	(*CreateAnimalRequest)(nil),   // 4: pkg.proto.v1.CreateAnimalRequest
	(*CreateAnimalResponse)(nil),  // 5: pkg.proto.v1.CreateAnimalResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_pkg_proto_v1_animals_proto_depIdxs = []int32{
	0, // 0: pkg.proto.v1.Animal.animal_type:type_name -> pkg.proto.v1.AnimalType
	6, // 1: pkg.proto.v1.Animal.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: pkg.proto.v1.GetAnimalResponse.animal:type_name -> pkg.proto.v1.Animal
	0, // 3: pkg.proto.v1.CreateAnimalRequest.animal_type:type_name -> pkg.proto.v1.AnimalType
	1, // 4: pkg.proto.v1.CreateAnimalResponse.animal:type_name -> pkg.proto.v1.Animal
	2, // 5: pkg.proto.v1.AnimalsService.GetAnimal:input_type -> pkg.proto.v1.GetAnimalRequest
	4, // 6: pkg.proto.v1.AnimalsService.CreateAnimal:input_type -> pkg.proto.v1.CreateAnimalRequest
	3, // 7: pkg.proto.v1.AnimalsService.GetAnimal:output_type -> pkg.proto.v1.GetAnimalResponse
	5, // 8: pkg.proto.v1.AnimalsService.CreateAnimal:output_type -> pkg.proto.v1.CreateAnimalResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_v1_animals_proto_init() }
func file_pkg_proto_v1_animals_proto_init() {
	if File_pkg_proto_v1_animals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_v1_animals_proto_rawDesc), len(file_pkg_proto_v1_animals_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_v1_animals_proto_goTypes,
		DependencyIndexes: file_pkg_proto_v1_animals_proto_depIdxs,
		EnumInfos:         file_pkg_proto_v1_animals_proto_enumTypes,
		MessageInfos:      file_pkg_proto_v1_animals_proto_msgTypes,
	}.Build()
	File_pkg_proto_v1_animals_proto = out.File
	file_pkg_proto_v1_animals_proto_goTypes = nil
	file_pkg_proto_v1_animals_proto_depIdxs = nil
}
